#!/usr/bin/env bash
#
# Docker Toolbox - Quick Install Script
# Adds useful Docker command aliases to your shell configuration
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ASCII Banner
cat << "EOF"
    ____             __                ______            __ __
   / __ \____  _____/ /_____  _____   /_  __/___  ____  / / /_  ____  _  __
  / / / / __ \/ ___/ //_/ _ \/ ___/    / / / __ \/ __ \/ / __ \/ __ \| |/_/
 / /_/ / /_/ / /__/ ,< /  __/ /       / / / /_/ / /_/ / / /_/ / /_/ />  <
/_____/\____/\___/_/|_|\___/_/       /_/  \____/\____/_/_.___/\____/_/|_|

EOF

echo -e "${BLUE}Docker Toolbox - Quick Install${NC}"
echo ""

# Detect shell
SHELL_NAME=$(basename "$SHELL")
case "$SHELL_NAME" in
    bash)
        CONFIG_FILE="$HOME/.bashrc"
        ;;
    zsh)
        CONFIG_FILE="$HOME/.zshrc"
        ;;
    *)
        echo -e "${RED}Unsupported shell: $SHELL_NAME${NC}"
        echo "Supported shells: bash, zsh"
        exit 1
        ;;
esac

echo -e "Detected shell: ${GREEN}$SHELL_NAME${NC}"
echo -e "Config file: ${GREEN}$CONFIG_FILE${NC}"
echo ""

# Check if Docker is installed
if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed${NC}"
    echo "Please install Docker first: https://docs.docker.com/get-docker/"
    exit 1
fi

echo -e "${GREEN}✓ Docker is installed${NC}"
echo ""

# Ask which tools to install
echo "Select tools to install (or 'all' for everything):"
echo ""
echo "  1) Essential (Python, Node, jq, prettier)"
echo "  2) Programming Languages (Python, Node, Go, Ruby)"
echo "  3) Terminal Tools (bat, ripgrep, fd, jq, yq)"
echo "  4) DevOps (Docker, Git tools)"
echo "  5) All tools"
echo "  6) Custom selection"
echo ""
read -p "Enter your choice [1-6]: " choice

# Function to add aliases to config file
add_aliases() {
    local category=$1

    # Backup config file
    cp "$CONFIG_FILE" "${CONFIG_FILE}.backup.$(date +%s)"
    echo -e "${GREEN}✓ Backed up $CONFIG_FILE${NC}"

    # Check if aliases already exist
    if grep -q "# Docker Toolbox aliases" "$CONFIG_FILE"; then
        echo -e "${YELLOW}! Docker Toolbox aliases already exist in $CONFIG_FILE${NC}"
        read -p "Overwrite? [y/N]: " overwrite
        if [[ ! "$overwrite" =~ ^[Yy]$ ]]; then
            echo "Installation cancelled"
            exit 0
        fi
        # Remove old aliases
        sed -i.tmp '/# Docker Toolbox aliases/,/# End Docker Toolbox aliases/d' "$CONFIG_FILE"
    fi

    # Add new aliases
    cat >> "$CONFIG_FILE" << 'ALIASES'

# Docker Toolbox aliases
# Generated by https://github.com/yourusername/docker-toolbox

ALIASES

    case $category in
        essential|all)
            cat >> "$CONFIG_FILE" << 'ALIASES'
# Essential tools
alias dpy='docker run --rm -it -v ${PWD}:/app -w /app python:3.12 python'
alias dnode='docker run --rm -it -v ${PWD}:/app -w /app node:22 node'
alias jupyter='docker run --rm -p 8888:8888 -v ${PWD}:/home/jovyan/work jupyter/base-notebook'
alias prettier='docker run --rm -v ${PWD}:/work tmknom/prettier'
alias jq='docker run --rm -i ghcr.io/jqlang/jq'

ALIASES
            ;&
        languages|all)
            cat >> "$CONFIG_FILE" << 'ALIASES'
# Programming Languages
alias dpip='docker run --rm -v ${PWD}:/app -w /app python:3.12 pip'
alias jupyterlab='docker run --rm -p 8888:8888 -v ${PWD}:/home/jovyan/work jupyter/datascience-notebook'
alias jupyter-scipy='docker run --rm -p 8888:8888 -v ${PWD}:/home/jovyan/work jupyter/scipy-notebook'
alias dnpm='docker run --rm -v ${PWD}:/app -w /app node:22 npm'
alias dgo='docker run --rm -v ${PWD}:/app -w /app golang:1.22 go'
alias druby='docker run --rm -it -v ${PWD}:/app -w /app ruby:3.3 ruby'

ALIASES
            ;&
        terminal|all)
            cat >> "$CONFIG_FILE" << 'ALIASES'
# Terminal Tools
alias rg='docker run --rm -v ${PWD}:/data -w /data alpine sh -c "apk add --no-cache ripgrep > /dev/null 2>&1 && rg"'
alias yq='docker run --rm -v ${PWD}:/workdir mikefarah/yq'
alias lazygit='docker run --rm -it -v ${PWD}:/repo -w /repo lazyteam/lazygit'
alias lazydocker='docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock lazyteam/lazydocker'

ALIASES
            ;&
        devops|all)
            cat >> "$CONFIG_FILE" << 'ALIASES'
# DevOps Tools
alias dgit='docker run --rm -v ${PWD}:/git -w /git alpine/git'
alias trivy='docker run --rm aquasec/trivy'

ALIASES
            ;;
    esac

    cat >> "$CONFIG_FILE" << 'ALIASES'
# End Docker Toolbox aliases

ALIASES

    echo -e "${GREEN}✓ Aliases added to $CONFIG_FILE${NC}"
}

# Install based on choice
case $choice in
    1)
        add_aliases "essential"
        ;;
    2)
        add_aliases "languages"
        ;;
    3)
        add_aliases "terminal"
        ;;
    4)
        add_aliases "devops"
        ;;
    5)
        add_aliases "all"
        ;;
    6)
        echo "Custom selection not yet implemented"
        echo "Please manually copy aliases from docker-dev-tools.md"
        exit 0
        ;;
    *)
        echo -e "${RED}Invalid choice${NC}"
        exit 1
        ;;
esac

echo ""
echo -e "${GREEN}✓ Installation complete!${NC}"
echo ""
echo "To start using the aliases, run:"
echo -e "  ${YELLOW}source $CONFIG_FILE${NC}"
echo ""
echo "Or restart your terminal."
echo ""
echo -e "View all available tools: ${BLUE}https://github.com/yourusername/docker-toolbox/blob/main/docker-dev-tools.md${NC}"
