#Requires -Version 5.1
<#
.SYNOPSIS
    Docker Toolbox - Quick Install Script for Windows
.DESCRIPTION
    Adds useful Docker command functions to your PowerShell profile
.NOTES
    Run with: .\install.ps1
    Or: powershell -ExecutionPolicy Bypass -File install.ps1
#>

# Colors for output
$Script:Colors = @{
    Red    = 'Red'
    Green  = 'Green'
    Yellow = 'Yellow'
    Blue   = 'Cyan'
    White  = 'White'
}

# ASCII Banner
function Show-Banner {
    Write-Host @"
    ____             __                ______            __ __
   / __ \____  _____/ /_____  _____   /_  __/___  ____  / / /_  ____  _  __
  / / / / __ \/ ___/ //_/ _ \/ ___/    / / / __ \/ __ \/ / __ \/ __ \| |/_/
 / /_/ / /_/ / /__/ ,< /  __/ /       / / / /_/ / /_/ / / /_/ / /_/ />  <
/_____/\____/\___/_/|_|\___/_/       /_/  \____/\____/_/_.___/\____/_/|_|

"@ -ForegroundColor $Colors.Blue

    Write-Host 'Docker Toolbox - Quick Install (Windows)' -ForegroundColor $Colors.Blue
    Write-Host ''
}

# Write colored message
function Write-ColorMessage {
    param(
        [string]$Message,
        [string]$Color = 'White',
        [switch]$NoNewline
    )

    if ($NoNewline) {
        Write-Host $Message -ForegroundColor $Colors[$Color] -NoNewline
    } else {
        Write-Host $Message -ForegroundColor $Colors[$Color]
    }
}

# Check if Docker is installed
function Test-DockerInstalled {
    try {
        $null = docker --version 2>$null
        return $true
    } catch {
        return $false
    }
}

# Get or create PowerShell profile
function Initialize-Profile {
    if (-not (Test-Path $PROFILE)) {
        Write-ColorMessage '! PowerShell profile does not exist, creating it...' 'Yellow'
        New-Item -Path $PROFILE -ItemType File -Force | Out-Null
        Write-ColorMessage "[OK] Created PowerShell profile at: $PROFILE" 'Green'
    } else {
        Write-ColorMessage "[OK] Found PowerShell profile at: $PROFILE" 'Green'
    }
    Write-Host ''
}

# Backup profile
function Backup-Profile {
    $timestamp = Get-Date -Format 'yyyyMMddHHmmss'
    $backupPath = "$PROFILE.backup.$timestamp"
    Copy-Item -Path $PROFILE -Destination $backupPath -Force
    Write-ColorMessage "[OK] Backed up profile to: $backupPath" 'Green'
}

# Check if aliases already exist
function Test-AliasesExist {
    $content = Get-Content $PROFILE -Raw -ErrorAction SilentlyContinue
    return $content -match '# Docker Toolbox functions'
}

# Remove old aliases
function Remove-OldAliases {
    $content = Get-Content $PROFILE -Raw
    $pattern = '(?s)# Docker Toolbox functions.*?# End Docker Toolbox functions\r?\n'
    $newContent = $content -replace $pattern, ''
    Set-Content -Path $PROFILE -Value $newContent -NoNewline
}

# Add functions to profile
function Add-Functions {
    param(
        [string]$Category,
        [string]$Prefix
    )

    Backup-Profile

    # Check if aliases already exist
    if (Test-AliasesExist) {
        Write-ColorMessage '! Docker Toolbox functions already exist in your profile' 'Yellow'
        $overwrite = Read-Host 'Overwrite? [y/N]'
        if ($overwrite -notmatch '^[Yy]$') {
            Write-Host 'Installation cancelled'
            exit 0
        }
        Remove-OldAliases
    }

    # Build functions as array of strings
    $functions = @()
    $functions += ''
    $functions += '# Docker Toolbox functions'
    $functions += '# Generated by https://github.com/yourusername/docker-toolbox'
    $functions += ''

    # Add functions based on category
    if ($Category -in 'essential', 'all') {
        $functions += '# Essential tools'
        $functions += "function $Prefix" + 'python { docker run --rm -it -v ${PWD}:/app -w /app python:3.12 python $args }'
        $functions += "function $Prefix" + 'node { docker run --rm -it -v ${PWD}:/app -w /app node:22 node $args }'
        $functions += "function $Prefix" + 'jupyter { docker run --rm -p 8888:8888 -v ${PWD}:/home/jovyan/work jupyter/base-notebook }'
        $functions += "function $Prefix" + 'prettier { docker run --rm -v ${PWD}:/work tmknom/prettier $args }'
        $functions += "function $Prefix" + 'jq { $input | docker run --rm -i ghcr.io/jqlang/jq $args }'
        $functions += ''
    }

    if ($Category -in 'languages', 'all') {
        $functions += '# Programming Languages'
        $functions += "function $Prefix" + 'pip { docker run --rm -v ${PWD}:/app -w /app python:3.12 pip $args }'
        $functions += "function $Prefix" + 'jupyterlab { docker run --rm -p 8888:8888 -v ${PWD}:/home/jovyan/work jupyter/datascience-notebook }'
        $functions += "function $Prefix" + 'jupyter-scipy { docker run --rm -p 8888:8888 -v ${PWD}:/home/jovyan/work jupyter/scipy-notebook }'
        $functions += "function $Prefix" + 'npm { docker run --rm -v ${PWD}:/app -w /app node:22 npm $args }'
        $functions += "function $Prefix" + 'go { docker run --rm -v ${PWD}:/app -w /app golang:1.22 go $args }'
        $functions += "function $Prefix" + 'ruby { docker run --rm -it -v ${PWD}:/app -w /app ruby:3.3 ruby $args }'
        $functions += ''
    }

    if ($Category -in 'terminal', 'all') {
        $functions += '# Terminal Tools'
        $functions += "function $Prefix" + 'rg { docker run --rm -v ${PWD}:/data -w /data alpine sh -c ' + [char]34 + 'apk add --no-cache ripgrep > /dev/null 2>&1 && rg $args' + [char]34 + ' }'
        $functions += "function $Prefix" + 'yq { docker run --rm -v ${PWD}:/workdir mikefarah/yq $args }'
        $functions += "function $Prefix" + 'lazygit { docker run --rm -it -v ${PWD}:/repo -w /repo lazyteam/lazygit }'
        $functions += "function $Prefix" + 'lazydocker { docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock lazyteam/lazydocker }'
        $functions += ''
    }

    if ($Category -in 'devops', 'all') {
        $functions += '# DevOps Tools'
        $functions += "function $Prefix" + 'git { docker run --rm -v ${PWD}:/git -w /git alpine/git $args }'
        $functions += "function $Prefix" + 'trivy { docker run --rm aquasec/trivy $args }'
        $functions += ''
    }

    $functions += '# End Docker Toolbox functions'
    $functions += ''

    # Write all content at once
    $functions | ForEach-Object { Add-Content -Path $PROFILE -Value $_ }

    Write-ColorMessage '[OK] Functions added to PowerShell profile' 'Green'
}

# Main script
Clear-Host
Show-Banner

# Check PowerShell version
if ($PSVersionTable.PSVersion.Major -lt 5) {
    Write-ColorMessage 'Error: PowerShell 5.1 or higher is required' 'Red'
    Write-Host "Your version: $($PSVersionTable.PSVersion)"
    exit 1
}

# Check Docker installation
Write-Host 'Checking for Docker...'
if (-not (Test-DockerInstalled)) {
    Write-ColorMessage 'Error: Docker is not installed' 'Red'
    Write-Host 'Please install Docker first: https://docs.docker.com/get-docker/'
    exit 1
}

Write-ColorMessage '[OK] Docker is installed' 'Green'
Write-Host ''

# Initialize profile
Initialize-Profile

# Ask which tools to install
Write-Host "Select tools to install (or `"all`" for everything):"
Write-Host ''
Write-Host '  1) Essential (Python, Node, jq, prettier)'
Write-Host '  2) Programming Languages (Python, Node, Go, Ruby)'
Write-Host '  3) Terminal Tools (ripgrep, yq, lazygit, lazydocker)'
Write-Host '  4) DevOps (Git tools, Trivy)'
Write-Host '  5) All tools'
Write-Host '  6) Custom selection'
Write-Host ''
$choice = Read-Host 'Enter your choice [1-6]'

Write-Host ''
Write-Host "Use `"dt-`" prefix for functions? (Recommended to avoid conflicts)"
Write-Host 'Examples: dt-python instead of python, dt-node instead of node'
Write-Host ''
$usePrefix = Read-Host 'Use dt- prefix? [Y/n]'
if ([string]::IsNullOrWhiteSpace($usePrefix)) { $usePrefix = 'Y' }

$prefix = if ($usePrefix -match '^[Yy]$') { 'dt-' } else { '' }

# Install based on choice
$category = switch ($choice) {
    '1' { 'essential' }
    '2' { 'languages' }
    '3' { 'terminal' }
    '4' { 'devops' }
    '5' { 'all' }
    '6' {
        Write-ColorMessage 'Custom selection not yet implemented' 'Yellow'
        Write-Host 'Please manually copy functions from docker-dev-tools.md'
        exit 0
    }
    default {
        Write-ColorMessage 'Invalid choice' 'Red'
        exit 1
    }
}

Write-Host ''
Add-Functions -Category $category -Prefix $prefix

# Summary
Write-Host ''
Write-ColorMessage '═══════════════════════════════════════════════════════' 'Green'
Write-ColorMessage '[OK] Installation complete!' 'Green'
Write-ColorMessage '═══════════════════════════════════════════════════════' 'Green'
Write-Host ''
Write-Host 'Functions have been added to your PowerShell profile:'
Write-ColorMessage "  $PROFILE" 'Yellow'
Write-Host ''
Write-Host 'To start using the functions, run:'
Write-ColorMessage '  . $PROFILE' 'Yellow'
Write-Host ''
Write-Host 'Or restart your PowerShell session.'
Write-Host ''
Write-ColorMessage 'View all available tools:' 'Blue'
Write-ColorMessage '  https://github.com/yourusername/docker-toolbox/blob/main/docker-dev-tools.md' 'Blue'
Write-Host ''

# Keep window open
pause
